const streams = [
  "--Select--",
  "Agriculture",
  "Architecture and Town Planning",
  "Arts",
  "Commerce",
  "Commerce & Management",
  "Commerce Management",
  "Design",
  "Education",
  "Engineering",
  "Engineering Machine Group",
  "Engineering Non Machine Group",
  "Eye Care Optometrists",
  "Fine Art (Visual Art)",
  "Health Science",
  "Hotel Management and Catering",
  "Humanities and Social Sciences",
  "Interdisciplinary",
  "Law",
  "Management",
  "MCA",
  "Non Engineering Group",
  "Non-AICTE",
  "Nursing",
  "Other",
  "Pharmacy",
  "Physical Education",
  "Science",
  "Science Technology",
  "Social Work",
  "Veterinary"
];

export default streams;
